import { ShriramFund } from './types'

export const SHRIRAM_FUNDS: ShriramFund[] = [
  {
    id: 'SMAF',
    name: 'Shriram Multi Asset Allocation Fund',
    shortName: 'Multi Asset',
    category: 'MULTI_ASSET',
    riskLevel: 'Moderately High',
    riskScore: 3,
    minHorizonMonths: 36,
    maxHorizonMonths: 240,
    expenseRatio: 1.85,
    fiveYearReturn: 14.2,
    threeYearReturn: 12.8,
    oneYearReturn: 18.4,
    aum: 1240,
    peerPercentile: 72,
    goalTags: ['RETIREMENT', 'CHILD_FUTURE', 'HOME', 'BIG_PURCHASE'],
    description: 'Holds equity, debt and gold together (at least 10% in each). When equities fall, the debt and gold portions cushion the drop, so the ride is far smoother than a pure-equity fund. The manager rebalances across the three asset classes as markets move.',
    assetMix: 'Equity + Debt + Gold',
    bestFor: 'Cautious or first-time investors, anyone who would be anxious in a crash, or shorter (3–6 year) horizons — the steadiest all-weather choice.',
    drawdownNote: 'Shallowest falls of the three — gold and debt typically hold up when equities drop.',
    taxNote: 'Equity taxation when equity ≥ 65%: LTCG 12.5% after 1 year',
  },
  {
    id: 'SFC',
    name: 'Shriram Flexi Cap Fund',
    shortName: 'Flexi Cap',
    category: 'FLEXI_CAP',
    riskLevel: 'High',
    riskScore: 4,
    minHorizonMonths: 60,
    maxHorizonMonths: 360,
    expenseRatio: 1.95,
    fiveYearReturn: 16.8,
    threeYearReturn: 14.5,
    oneYearReturn: 22.1,
    aum: 890,
    peerPercentile: 81,
    goalTags: ['RETIREMENT', 'CHILD_FUTURE', 'HOME'],
    description: 'A pure-equity fund. The manager invests freely across large, mid and small-cap companies — no fixed limits — to chase the best opportunities. Highest long-term growth potential of the three, and the sharpest swings.',
    assetMix: 'Pure equity (large + mid + small cap)',
    bestFor: 'Experienced, risk-tolerant investors with a long (7+ year) horizon who can stay calm through market crashes.',
    drawdownNote: 'Deepest falls of the three — no debt or gold cushion. Needs a long horizon to recover.',
    taxNote: 'Equity taxation: LTCG 12.5% after 1 year; STCG 20%',
  },
  {
    id: 'SAH',
    name: 'Shriram Aggressive Hybrid Fund',
    shortName: 'Aggressive Hybrid',
    category: 'AGGRESSIVE_HYBRID',
    riskLevel: 'Moderately High',
    riskScore: 3,
    minHorizonMonths: 36,
    maxHorizonMonths: 180,
    expenseRatio: 1.90,
    fiveYearReturn: 13.6,
    threeYearReturn: 11.9,
    oneYearReturn: 17.2,
    aum: 620,
    peerPercentile: 68,
    goalTags: ['CHILD_FUTURE', 'HOME', 'BIG_PURCHASE', 'RETIREMENT'],
    description: 'Keeps 65–80% in equity for growth and 20–35% in debt as a shock-absorber. The balanced middle path — more growth than a multi-asset fund, a steadier ride than pure equity.',
    assetMix: 'Equity (65–80%) + Debt (20–35%)',
    bestFor: 'Moderate-risk investors with a medium-to-long (5+ year) horizon who want real equity growth but a smoother ride than a pure-equity fund.',
    drawdownNote: 'Moderate falls — the debt portion softens equity drops, but there is no gold cushion.',
    taxNote: 'Equity taxation: LTCG 12.5% after 1 year',
  },
  {
    id: 'SLC',
    name: 'Shriram Large Cap Fund',
    shortName: 'Large Cap',
    category: 'LARGE_CAP',
    riskLevel: 'Moderately High',
    riskScore: 3,
    minHorizonMonths: 60,
    maxHorizonMonths: 300,
    expenseRatio: 1.75,
    fiveYearReturn: 14.9,
    threeYearReturn: 13.2,
    oneYearReturn: 19.8,
    aum: 780,
    peerPercentile: 64,
    goalTags: ['RETIREMENT', 'CHILD_FUTURE', 'HOME'],
    description: 'Invests in top 100 companies by market cap. Lower volatility than mid/small cap with strong long-term compounding.',
    taxNote: 'LTCG at 12.5% after 1 year; STCG at 20%',
  },
  {
    id: 'SRS',
    name: 'Shriram Regular Savings Fund',
    shortName: 'Regular Savings',
    category: 'REGULAR_SAVINGS',
    riskLevel: 'Low',
    riskScore: 2,
    minHorizonMonths: 12,
    maxHorizonMonths: 84,
    expenseRatio: 1.20,
    fiveYearReturn: 8.4,
    threeYearReturn: 7.8,
    oneYearReturn: 9.1,
    aum: 340,
    peerPercentile: 59,
    goalTags: ['EMERGENCY', 'BIG_PURCHASE'],
    description: 'Conservative hybrid with 75-90% debt. Stable returns better than FD with low volatility — ideal for near-term goals.',
    taxNote: 'Taxed as debt fund — at income tax slab rate',
  },
  {
    id: 'SLQ',
    name: 'Shriram Liquid Fund',
    shortName: 'Liquid',
    category: 'LIQUID',
    riskLevel: 'Very Low',
    riskScore: 1,
    minHorizonMonths: 1,
    maxHorizonMonths: 12,
    expenseRatio: 0.30,
    fiveYearReturn: 6.8,
    threeYearReturn: 6.5,
    oneYearReturn: 7.2,
    aum: 1850,
    peerPercentile: 70,
    goalTags: ['EMERGENCY'],
    description: 'Invests in money market instruments with maturity up to 91 days. Instant redemption available — your emergency corpus home.',
    taxNote: 'Taxed at income tax slab rate',
  },
  {
    id: 'SON',
    name: 'Shriram Overnight Fund',
    shortName: 'Overnight',
    category: 'OVERNIGHT',
    riskLevel: 'Very Low',
    riskScore: 1,
    minHorizonMonths: 1,
    maxHorizonMonths: 6,
    expenseRatio: 0.15,
    fiveYearReturn: 6.2,
    threeYearReturn: 6.0,
    oneYearReturn: 6.8,
    aum: 920,
    peerPercentile: 61,
    goalTags: ['EMERGENCY'],
    description: 'Safest fund in the universe — overnight securities only. Lower return than Liquid but maximum safety for short-term parking.',
    taxNote: 'Taxed at income tax slab rate',
  },
  {
    id: 'SSD',
    name: 'Shriram Short Duration Fund',
    shortName: 'Short Duration',
    category: 'SHORT_DURATION',
    riskLevel: 'Low',
    riskScore: 2,
    minHorizonMonths: 12,
    maxHorizonMonths: 48,
    expenseRatio: 0.65,
    fiveYearReturn: 7.6,
    threeYearReturn: 7.1,
    oneYearReturn: 8.3,
    aum: 510,
    peerPercentile: 66,
    goalTags: ['EMERGENCY', 'BIG_PURCHASE'],
    description: 'Debt fund with 1-3 year maturity profile. Better than FD rates with tax-efficient treatment for investors in higher tax brackets.',
    taxNote: 'Taxed at income tax slab rate',
  },
]

export const FUND_BY_ID = Object.fromEntries(SHRIRAM_FUNDS.map(f => [f.id, f]))

// The three growth funds the engine recommends from — one is shown to the user.
// SMAF = Multi Asset (most defensive) · SAH = Aggressive Hybrid (balanced) · SFC = Flexi Cap (most aggressive)
export const CORE_FUND_IDS = ['SMAF', 'SAH', 'SFC'] as const
export const CORE_FUNDS = CORE_FUND_IDS.map(id => FUND_BY_ID[id])

export function formatCurrency(amount: number): string {
  if (amount >= 10_000_000) {
    return `Rs. ${(amount / 10_000_000).toFixed(2)} Cr`
  } else if (amount >= 100_000) {
    return `Rs. ${(amount / 100_000).toFixed(2)} Lakh`
  } else {
    return `Rs. ${amount.toLocaleString('en-IN')}`
  }
}

export function formatSIPAmount(amount: number): string {
  return `Rs. ${amount.toLocaleString('en-IN')}/month`
}
